// Gatherings
export const LOAD_GATHERINGS = 'LOAD_GATHERINGS';
export const JOIN_GATHERING = 'JOIN_GATHERING';
export const ACTIVATE_GATHERING_START = 'ACTIVATE_GATHERING_START';
export const ACTIVATE_GATHERING_SUCCESS = 'ACTIVATE_GATHERING_SUCCESS';
export const ACTIVATE_GATHERING_FAIL = 'ACTIVATE_GATHERING_FAIL';
export const DEACTIVATE_GATHERING = 'DEACTIVATE_GATHERING';
export const NO_ACTIVE_GATHERING = 'NO_ACTIVE_GATHERING';

// Contacts
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CONNECT_INIT = 'CONNECT_INIT';
export const CONNECT_START = 'CONNECT_START';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAIL = 'CONNECT_FAIL';
export const RECOMMEND_START = 'RECCOMMEND_START';
export const RECOMMEND_SUCCESS = 'RECCOMMEND_SUCCESS';
export const RECOMMEND_FAIL = 'RECCOMMEND_FAIL';
export const ADD_STAR = 'ADD_STAR';

// Connections
export const ADD_STAR_TO_CONNECTION = 'ADD_STAR_TO_CONNECTION';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
export const LOAD_CONNECTIONS = 'LOAD_CONNECTIONS';
export const UPDATE_AWARDS_START = 'UPDATE_AWARDS_START';
export const UPDATE_AWARDS_SUCCESS = 'UPDATE_AWARDS_SUCCESS';
export const UPDATE_AWARDS_FAIL = 'UPDATE_AWARDS_FAIL';
export const LOAD_AWARDS = 'LOAD_AWARDS';

// Network
export const ADD_PEER = 'ADD_PEER';
export const REMOVE_PEER = 'REMOVE_PEER';
